version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    ports:
      - "8081:80"
    volumes:
      - "./:/var/www/html"
      - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: laravel_mysql
    ports:
      - "3311:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_SERVICE_NAME: mysql
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php
    ports:
      - "9000"
    volumes:
      - "./:/var/www/html"
    depends_on:
      - mysql
    networks:
      - laravel

networks:
  laravel:
volumes:
  mysql:
